# Generated by Django 4.1.3 on 2025-03-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
