# Generated by Django 4.1.3 on 2025-04-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='precio',
            new_name='price',
        ),
    ]
