# Generated by Django 5.1.6 on 2025-04-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item'),
        ('restaurant', '0003_menu_description'),
    ]

    operations = [
    ]
