# Generated by Django 5.1.6 on 2025-04-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_merge_0002_menu_menu_item_0003_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='menu_item_description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_item',
        ),
    ]
